//车辆管理
import Backbone from 'backbone';
var vehicle = Backbone.Model.extend({
    defaults:{
        id:'',
        headImg:'',
        status:'',
        vehicleCode:{
            name:'vehicleCode',
            aliasName:'车辆编码',
            value:'',
            isShowInCard:''
        },
        vehicleNumber:{
            name:'vehicleNumber',
            aliasName:'车牌号',
            value:'',
            isShowInCard:''
        },
        vehicleBrand:{
            name:'vehicleBrand',
            aliasName:'车辆品牌',
            value:'',
            isShowInCard:''
        },
        vehicleModel:{
            name:'vehicleModel',
            aliasName:'车辆型号',
            value:'',
            isShowInCard:''
        },
        vehicleType:{
            name:'vehicleType',
            aliasName:'车辆类型',
            value:'',
            isShowInCard:''
        },
        tag:{
            name:'tag',
            aliasName:'标签',
            value:'',
            isShowInCard:''
        },
        color:{
            name:'color',
            aliasName:'颜色',
            value:'',
            isShowInCard:''
        },
        vehicleLoad:{
            name:'vehicleLoad',
            aliasName:'载重（吨）',
            value:'',
            isShowInCard:''
        },
        vehicleStatus:{
            name:'vehicleStatus',
            aliasName:'车辆状态',
            value:'',
            isShowInCard:''
        },
        seatNumber:{
            name:'seatNumber',
            aliasName:'座位数',
            value:'',
            isShowInCard:''
        },
        fuelEfficient:{
            name:'fuelEfficient',
            aliasName:'油耗',
            value:'',
            isShowInCard:''
        },
        ownerPhone:{
            name:'ownerPhone',
            aliasName:'车主手机',
            value:'',
            isShowInCard:''
        },
        ownerTeam:{
            name:'ownerTeam',
            aliasName:'所属车队',
            value:'',
            isShowInCard:''
        },
        oilCard:{
            name:'oilCard',
            aliasName:'油卡编号',
            value:'',
            isShowInCard:''
        },
        continuation:{
            name:'continuation',
            aliasName:'续航里程（电车）',
            value:'',
            isShowInCard:''
        },
        initialMileage:{
            name:'initialMileage',
            aliasName:'初始里程',
            value:'',
            isShowInCard:''
        },
        engineCode:{
            name:'engineCode',
            aliasName:'发动机号',
            value:'',
            isShowInCard:''
        },
        frameCode:{
            name:'frameCode',
            aliasName:'车架号',
            value:'',
            isShowInCard:''
        },
        buyCompany:{
            name:'buyCompany',
            aliasName:'购入单位',
            value:'',
            isShowInCard:''
        },
        price:{
            name:'price',
            aliasName:'购入价格',
            value:'',
            isShowInCard:''
        },
        buyData:{
            name:'buyData',
            aliasName:'购入日期',
            value:'',
            isShowInCard:''
        },
        driver:{
            name:'driver',
            aliasName:'司机',
            value:'',
            isShowInCard:''
        },
        driverPhone:{
            name:'driverPhone',
            aliasName:'司机手机',
            value:'',
            isShowInCard:''
        },
        section:{
            name:'section',
            aliasName:'所属部门',
            value:'',
            isShowInCard:''
        },
        onwerPeople:{
            name:'onwerPeople',
            aliasName:'所属车主',
            value:'',
            isShowInCard:''
        },
        outAge:{
            name:'outAge',
            aliasName:'是否停用',
            value:'',
            isShowInCard:''
        },
        remark:{
            name:'remark',
            aliasName:'备注',
            value:'',
            isShowInCard:''
        },
        electricCard:{
            name:'electricCard',
            aliasName:'电卡编号',
            value:'',
            isShowInCard:''
        }
    }
});
var vehicleCollection = Backbone.Collection.extend({
    model:vehicle
});
var vehicleDataModel = [];
for(let i = 0; i < 100 ; i++){
    vehicleDataModel.push({
        id:i,
        headImg:'/img/vehicle-header.png',
        status:`${i%2}`,
        vehicleCode:{
            name:'vehicleCode',
            aliasName:'车辆编码',
            value:`${i}`
        },
        vehicleNumber:{
            name:'vehicleNumber',
            aliasName:'车牌号',
            value:`车牌号${i}`,
            isShowInCard:true
        },
        vehicleBrand:{
            name:'vehicleBrand',
            aliasName:'车辆品牌',
            value:`车辆品牌${i}`,
            isShowInCard:false
        },
        vehicleModel:{
            name:'vehicleModel',
            aliasName:'车辆型号',
            value:`车辆型号${i}`,
            isShowInCard:false
        },
        type:`${i%3}`,
        tag:{
            name:'tag',
            aliasName:'标签',
            value:`标签${i}`,
            isShowInCard:true
        },
        color:{
            name:'color',
            aliasName:'颜色',
            value:`颜色${i}`,
            isShowInCard:false
        },
        vehicleLoad:{
            name:'vehicleLoad',
            aliasName:'载重（吨）',
            value:`载重${i}`,
            isShowInCard:false
        },
        vehicleStatus:{
            name:'vehicleStatus',
            aliasName:'车辆状态',
            value:`车辆状态${i}`,
            isShowInCard:false
        },
        seatNumber:{
            name:'seatNumber',
            aliasName:'座位数',
            value:`座位数${i}`,
            isShowInCard:true
        },
        fuelEfficient:{
            name:'fuelEfficient',
            aliasName:'油耗',
            value:`油耗${i}`,
            isShowInCard:false
        },
        ownerPhone:{
            name:'ownerPhone',
            aliasName:'车主手机',
            value:`车主手机${i}`,
            isShowInCard:false
        },
        ownerTeam:{
            name:'ownerTeam',
            aliasName:'所属车队',
            value:`所属车队${i}`,
            isShowInCard:false
        },
        oilCard:{
            name:'oilCard',
            aliasName:'油卡编号',
            value:`油卡编号${i}`,
            isShowInCard:false
        },
        continuation:{
            name:'continuation',
            aliasName:'续航里程（电车）',
            value:`续航里程${i}`,
            isShowInCard:false
        },
        initialMileage:{
            name:'initialMileage',
            aliasName:'初始里程',
            value:`初始里程${i}`,
            isShowInCard:false
        },
        engineCode:{
            name:'engineCode',
            aliasName:'发动机号',
            value:`发动机号${i}`,
            isShowInCard:false
        },
        frameCode:{
            name:'frameCode',
            aliasName:'车架号',
            value:`车架号${i}`,
            isShowInCard:false
        },
        buyCompany:{
            name:'buyCompany',
            aliasName:'购入单位',
            value:`购入单位${i}`,
            isShowInCard:false
        },
        price:{
            name:'price',
            aliasName:'购入价格',
            value:`购入价格${i}`,
            isShowInCard:false
        },
        buyData:{
            name:'buyData',
            aliasName:'购入日期',
            value:`购入日期${i}`,
            isShowInCard:false
        },
        driver:{
            name:'driver',
            aliasName:'司机',
            value:`司机${i}`,
            isShowInCard:false
        },
        driverPhone:{
            name:'driverPhone',
            aliasName:'司机手机',
            value:`司机手机${i}`,
            isShowInCard:false
        },
        section:{
            name:'section',
            aliasName:'所属部门',
            value:`所属部门${i}`,
            isShowInCard:false
        },
        onwerPeople:{
            name:'onwerPeople',
            aliasName:'所属车主',
            value:`所属车主${i}`,
            isShowInCard:false
        },
        outAge:{
            name:'outAge',
            aliasName:'是否停用',
            value:`是否停用${i}`,
            isShowInCard:false
        },
        remark:{
            name:'remark',
            aliasName:'备注',
            value:`备注${i}`,
            isShowInCard:true
        },
        electricCard:{
            name:'electricCard',
            aliasName:'电卡编号',
            value:`电卡编号${i}`,
            isShowInCard:false
        }
    })
}
let vehicleData = new vehicleCollection(vehicleDataModel);
let vehicleModel = new vehicle();
export{
    vehicleModel,vehicleData,vehicleCollection
}
